version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: ghosty-shop-bot
    restart: always
    environment:
      - BOT_TOKEN=8351638507:AAFSnnmblizuK7xOEleDiRl4SE4VTpPJulc
      - TZ=Europe/Kiev
    volumes:
      - ./data:/app/data
